import Head from "next/head";
import AppRight from "../components/AppRight";

export default function Home() {
  return (
    <div className="flex sm:flex-row flex-col-reverse justify-center items-center min-h-screen py-2 bg-gray ">
      <Head>
        <title>Create Next App </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
        <div className="flex w-2/3 max-w-4xl">
          <div
            style={{
              background:
                "url(https://images.unsplash.com/photo-1516939884455-1445c8652f83?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjN8fG91dGRvb3J8ZW58MHx8MHx8&auto=format&fit=crop&w=600&q=60)",
              flex: "0.6",
            }}
            className="font-poppins flex flex-col  w-3/5 p-5  justify-center items-center !bg-cover !bg-bottom object-contain rounded-l-2xl"
          >
            <h2 className="absolute top-10 left-20 text-4xl font-bold  text-blue ">
              PIXEL
            </h2>
            <div className="flex flex-col w-3/5">
              <h4 className="text-white text-left text-4xl font-semibold mt-10  ">
                Experience the future of image management with PIXER
              </h4>

              <button className="bg-orange w-60 text-white py-2 h-10 mt-10 px-5 rounded-xl">
                Join
              </button>
            </div>
          </div>
          <div className="w-2/5 " style={{ flex: "0.4" }}>
            <AppRight />
          </div>
        </div>
      </main>
    </div>
  );
}
